/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GithubScouter;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.MediaType;
import okhttp3.RequestBody;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class App {

    static String url = "https://api.github.com/graphql";
    static String inputFileName = "src\\main\\java\\GithubScouter\\token.txt";
    static String token = "";
    static OkHttpClient client = new OkHttpClient();

    public static void main(String[] args) {

        getToken();
        
        String requestMessage = "{\"query\":\"query{viewer{login}}\"}";
        String viewer = postToGithubAPI(requestMessage);

        System.out.println(viewer);
    }

    static String postToGithubAPI(String requestMessage) {
        String message = "";
        MediaType MIMEType = MediaType.parse("application/json; charset=utf-8");
        RequestBody requestBody = RequestBody.create(MIMEType, requestMessage);

        Request request = new Request.Builder()
            .url(url)
            .addHeader("Authorization", "bearer " + token)
            .post(requestBody)
            .build();

        try {
            Response response = client.newCall(request).execute();
            message = response.body().string();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        return message;
    }
    static void getToken() {
        try {
            File inputFile = new File(inputFileName);
            FileReader filereader = new FileReader(inputFile);
            int ch;
            while((ch = filereader.read()) != -1){
                token += (char)ch;
            }
            filereader.close();
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
            System.out.println("file not found.");
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
    
}